#!/usr/bin/env python3
####
#
# mcssh -- magento-cloud ssh helper tool
#
# expects a single argument, the project url (including the environment/branch name)
# no validation beyond ensuring that the format of the url is correct is done
#
# ex:
# $mcssh https://REGION.magento.cloud/projects/PROJECTID/environments/BRANCH
#
####


import os
import sys
import re

#error command (just in case)
def print_banner():
    banner = []
    in_banner = False
    try:
        with open(os.path.realpath(__file__), 'r') as f:
            for line in f:
                if line.strip() == '####':
                    if in_banner:
                        banner.append(line.rstrip())
                        break
                    in_banner = True
                if in_banner:
                    banner.append(line.rstrip())
        print('\n'.join(banner))
    except Exception:
        # Fallback if file reading fails
        print("mcssh -- magento-cloud ssh helper tool")

#is there an argument
if len(sys.argv) == 1:
    print_banner()
    sys.exit("Please provide an argument")

#get our url
ourUrl = re.sub(r"\/$","", re.sub('/#/','/',sys.argv[1]))

#experimental, convert branch .cloud urls (and hopefully catch wildcard subdomains)
match = re.search(r"https://(?:.*?\.?)?([^-]+)(?:-.*)?-([^-]+)\.([^.]+)\.magentosite\.cloud", ourUrl)
if match:
    env, proj_id, region = match.groups()
    ourUrl = f"https://{region}.magento.cloud/projects/{proj_id}/environments/{env}"

#regex validation
if not re.match( r"^http(s)://.*\.magento\.cloud\/projects\/[a-z0-9]+", ourUrl ):
    print_banner()
    print(ourUrl)
    sys.exit("Please verify and correct your branch URL")
    
#store project details in an array for later use
projDeets = str(ourUrl).split('/')

#seperate Id and Env (storing as different variables for possible code-reuse)
projId = " --project=" + str(projDeets[4])+" "
if re.match(r"^http(s)://.*\.magento\.cloud\/projects\/[a-z0-9]+\/environments\/.*", ourUrl ):
    projEnv = " --environment="+str(projDeets[6])+" "
else:
    os.system("magento-cloud "+projId+" environment:list|grep -v Inactive")
    projEnv = ""

#print url before running anything
print(ourUrl)

#run magento-cloud with the needed arguments to start a ssh session
os.system("magento-cloud " + projId + projEnv + " ssh")
