#!/usr/bin/python

####
#
#
# mssh -- magento-cloud ssh helper tool
#
# expects a single argument, the project url (including the environment/branch name
# no validation beyond ensuring that the format of the url is correct is done
#
# ex:
# $mssh https://REGION.magento.cloud/projects/PROJECTID/environments/BRANCH
#
####


import os
import sys
import re

#error command (just in case)
errMsg = "head -n 15 " + os.path.realpath(__file__) + "|tail -n 14"

#is there an argument
if len(sys.argv) == 1:
    os.system(errMsg)
    sys.exit("Please provide an argument")

#get our url
ourUrl = sys.argv[1]

#experimental, convert branch .cloud urls

if re.match("^http(s)://.*\.magentosite.cloud", ourUrl):
    converstep = re.sub("http(s)*://", "", str(ourUrl)).split('.')
    ourUrl = str('https://' + converstep[1] + '.magento.cloud/projects/' + str(converstep[0]).split("-")[2] + '/environments/' + str(converstep[0]).split("-")[0])
    print ourUrl

#regex validation
if not re.match( "^http(s)://.*\.magento\.cloud\/projects\/[a-z0-9]+\/environments\/.*", ourUrl ):
    os.system(errMsg)
    sys.exit("Please verify and correct your branch URL")
    
#store project details in an array for later use
projDeets = str(ourUrl).split('/')

#seperate Id and Env (storing as different variables for possible code-reuse)
projId = projDeets[4]
projEnv = projDeets[6]

#run magento-cloud with the needed arguments to start a ssh session
os.system("magento-cloud --project=" + projId + " --environment=" + projEnv + " ssh")
