#!/usr/bin/python

####
#
#
# mssh -- magento-cloud ssh helper tool
#
#
# expects a single argument, the project url (including the environment/branch name
# no validation beyond ensuring that the format of the url is correct is done
#
# ex:
# https://REGION.magento.cloud/projects/PROJECTID/environments/BRANCH
#
####


import os
import sys
import re

#is there an argument
if len(sys.argv) == 1:
    sys.exit("No arguments present")

#regex validation
if not re.match( "^https://.*\.magento\.cloud\/projects\/[a-z0-9]+\/environments\/.*", sys.argv[1] ):
      sys.exit("Invalid Argument")

#store project details in an array for later use
projDeets = str(sys.argv[1]).split('/')

#seperate Id and Env (storing as different variables for possible code-reuse)
projId = projDeets[4]
projEnv = projDeets[6]

#run magento-cloud with the needed arguments to start a ssh session
os.system("magento-cloud --project=" + projId + " --environment=" + projEnv + " ssh")
